data:
  pde: "heat"
  name: 'logt'
  datapath: 'data/heat_logt.hdf5'  # path to save the generated dataset

net:
  in_ch: 2
  label_ch: 2

training:
  batch_size: 64
  shuffle: True
  num_epochs: 500
  learning_rate: 1e-3
  weight_decay: 0.0

sampling:
  sample_shape: [2, 64, 64] # shape of single sample (C, H, W)
  batch_size: 32            # batch size for sampling
