data:
  pde: "heat"
  name: 'logt'
  datapath: 'data/heat_logt.hdf5'  # path to save the generated dataset

net:
  in_ch: 2
  label_ch: 2

training:
  batch_size: 64
  shuffle: True
  num_epochs: 500
  learning_rate: 1e-3
  weight_decay: 0.0

sampling:
  sample_shape: [2, 64, 64] # shape of single sample (C, H, W)
  batch_size: 32            # batch size for sampling
  ch_a: 1
  zeta_a: 50.0
  zeta_u: 5.0
  zeta_pde: 0.5
  num_steps: 50
  loss_func: "diffusion_pde.sampling.heat_loss"

validation:
  data_gen_func: "diffusion_pde.pdes.generate_heat"
  func_kwargs:
    N: 50
    B: 25
    steps: 50
    T: 0.5
    device: "cuda"
    seed: 12
    Lx: 1.0
    Ly: 1.0
    Nx: 64
    Ny: 64
    time_spacing: "lineart"