data:
  pde: 'llg'
  name: 'llg'
  datapath: 'data/llg.hdf5'  # path to save the generated dataset

start_at_t0: true        # whether to randomize initial time t0 for each sample
method: "joint"  # "joint" for learning forward and inverse, "forward" for forward only
loss: "edm" #  "edm" for standard EDM loss, "physics" for EDM with physics loss

net:
  in_ch: 6      # 2 * 3 for magnetization vector (m_x, m_y, m_z)
  label_ch: 4   # 3 for external field + 1 for time

training:
  batch_size: 32
  shuffle: True
  num_epochs: 1000
  learning_rate: 1e-4
  weight_decay: 0.0

sampling:
  sample_shape: [6, 64, 16] # shape of single sample (C, H, W)
  batch_size: 32            # batch size for sampling
  ch_a: 3
  zeta_a: 50.0
  zeta_u: 40.0
  zeta_pde: 0.4
  num_steps: 50
  loss_func: "diffusion_pde.sampling.heat_loss"