defaults:
  - dataset: heat_eq_logt_joint
  - model: unetv2
  - _self_

wandb:
  entity: 'philiphohwy-danmarks-tekniske-universitet-dtu'
  project: 'dynamical-pde-diffusion-final'
  dir: ${oc.env:REPO_ROOT,${oc.env:PWD}}/logs
  name: null
  mode: ${oc.env:WANDB_MODE, online} # set to 'offline' to disable online logging or 'disabled' to turn off wandb entirely
  
hydra:
  run:
    dir: ${oc.env:REPO_ROOT,${hydra:runtime.cwd}}/logs/hydra/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${oc.env:REPO_ROOT,${hydra:runtime.cwd}}/logs/hydra_multirun
    subdir: ${hydra.job.num}
  job:
    chdir: true #if broken, set to false
  
  output_subdir: .hydra

#model_save_path: ${oc.env:REPO_ROOT,${hydra:runtime.cwd}}/pretrained_models